### ISSUE TITLE
Implement User Auth

### ISSUE THREAD

**Issue by hwuethrich** [zebbra/data_aggregator#251]
Implement user auth using [ash_authentication](https://github.com/team-alembic/ash_authentication).

**Comment by chusi** [comment]
@sidler92 please open pull request for user auth

**Comment by sidler92** [comment]
#281 PR here
Very basic implementation: require authentication for select routes.
Tests are not yet fixed.
Templates also not yet touched.

**Comment by sidler92** [comment]
Basic policies implemented.
Starting with user admin view now.

**Comment by sidler92** [comment]
Creating the user administration view

**Comment by sidler92** [comment]
administration view - finishing up creation/edit modal

**Comment by chusi** [comment]
done and works
